
- name: Remove old container junk
  apt:
    state: absent
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containnerd
      - runc

- name: Install dependencies
  apt:
    state: present
    name: "{{ DOCKER_REQ }}"
    update_cache: yes
    force_apt_get: yes

- name: Add GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
  
- name: Add repo
  shell: |
    echo \
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      {{ ansible_lsb.codename }} stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update cache
  apt:
    update_cache: yes

- name: Install Docker Engine
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Non-root docker management -- groupadd
  group:
    name: docker
    state: present

- name: Non-root docker management -- usermod
  user:
    append: yes
    groups: docker
    name: moose

# - name: Non-root docker management -- newgrp
#   shell: newgrp docker
- name: Check if docker-compose is present
  stat:
    path: /usr/local/bin/docker-compose
  register: docker_compose_binary

- name: Download docker-compose
  shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  when: not docker_compose_binary.stat.exists

- name: Make compose executable
  shell: sudo chmod +x /usr/local/bin/docker-compose
  when: not docker_compose_binary.stat.exists

- name: Add docker-compose auto-completion
  shell: |
    sudo curl \
    -L https://raw.githubusercontent.com/docker/compose/1.29.2/contrib/completion/bash/docker-compose \
    -o /etc/bash_completion.d/docker-compose
  when: not docker_compose_binary.stat.exists
      
- name: Test installation
  shell: docker run hello-world

