# ansible-playbook provision.yaml --ask-become-pass -u

- name: Provision moose-one
  hosts: all
  gather_facts: yes
  remote_user: moose

  tasks:
    - name: Install docker
      include_role:
        name: install_docker
      vars:
        ansible_become: yes

    - name: Setup git repositories
      include_role:
        name: setup_repos

    - name: Setup mounts
      include_role:
        name: setup_mounts
      vars:
        ansible_become: yes